export const coursesData = [
  {
    id: 1,
    name: "Introduction to Computer Science",
    percentCompleted: 60,
    difficulty: "Beginner",
    rating: 4.5,
    imageSrc: "../assets/course.jpg",
  },
  {
    id: 2,
    name: "Data Structures and Algorithms",
    percentCompleted: 45,
    difficulty: "Intermediate",
    rating: 4.2,
    imageSrc: "../assets/course.jpg",
  },
  {
    id: 3,
    name: "Machine Learning Fundamentals",
    percentCompleted: 80,
    difficulty: "Intermediate",
    rating: 4.8,
    imageSrc: "../assets/course.jpg",
  },
  {
    id: 4,
    name: "Web Development Bootcamp",
    percentCompleted: 30,
    difficulty: "Intermediate",
    rating: 4.0,
    imageSrc: "../assets/course.jpg",
  },
  {
    id: 5,
    name: "Advanced Java Programming",
    percentCompleted: 75,
    difficulty: "Advanced",
    rating: 4.7,
    imageSrc: "../assets/course.jpg",
  },
  {
    id: 6,
    name: "Digital Marketing Strategies",
    percentCompleted: 40,
    difficulty: "Beginner",
    rating: 4.1,
    imageSrc: "../assets/course.jpg",
  },
  {
    id: 7,
    name: "Introduction to Artificial Intelligence",
    percentCompleted: 70,
    difficulty: "Intermediate",
    rating: 4.6,
    imageSrc: "../assets/course.jpg",
  },
  {
    id: 8,
    name: "Graphic Design Basics",
    percentCompleted: 55,
    difficulty: "Beginner",
    rating: 4.3,
    imageSrc: "../assets/course.jpg",
  },
  {
    id: 9,
    name: "Blockchain and Cryptocurrencies",
    percentCompleted: 90,
    difficulty: "Advanced",
    rating: 4.9,
    imageSrc: "../assets/course.jpg",
  },
  {
    id: 10,
    name: "Mobile App Development with React Native",
    percentCompleted: 65,
    difficulty: "Intermediate",
    rating: 4.4,
    imageSrc: "../assets/course.jpg",
  },
  {
    id: 11,
    name: "Business Ethics and Leadership",
    percentCompleted: 25,
    difficulty: "Beginner",
    rating: 3.9,
    imageSrc: "../assets/course.jpg",
  },
  {
    id: 12,
    name: "Game Development with Unity",
    percentCompleted: 50,
    difficulty: "Intermediate",
    rating: 4.2,
    imageSrc: "../assets/course.jpg",
  },
  {
    id: 13,
    name: "Python for Data Science",
    percentCompleted: 70,
    difficulty: "Intermediate",
    rating: 4.6,
    imageSrc: "../assets/course.jpg",
  },
  {
    id: 14,
    name: "Network Security Fundamentals",
    percentCompleted: 85,
    difficulty: "Advanced",
    rating: 4.8,
    imageSrc: "../assets/course.jpg",
  },
  {
    id: 15,
    name: "Creative Writing Workshop",
    percentCompleted: 35,
    difficulty: "Beginner",
    rating: 3.8,
    imageSrc: "../assets/course.jpg",
  },
];

export const notesData = [
  {
    id: 1,
    name: "Pandas CheatSheet",
    course: "Python Mastery",
    lecture: 25,
    pages: 10,
  },
  {
    id: 2,
    name: "JavaScript Basics",
    course: "Web Development",
    lecture: 15,
    pages: 5,
  },
  {
    id: 3,
    name: "Data Visualization Techniques",
    course: "Data Science Essentials",
    lecture: 30,
    pages: 15,
  },
  {
    id: 4,
    name: "React.js Quick Reference",
    course: "Frontend Development with React",
    lecture: 20,
    pages: 8,
  },
  {
    id: 5,
    name: "SQL Query Examples",
    course: "Database Management",
    lecture: 18,
    pages: 7,
  },
  {
    id: 6,
    name: "Machine Learning Concepts",
    course: "Advanced Data Science",
    lecture: 40,
    pages: 12,
  },
  {
    id: 7,
    name: "UX/UI Design Principles",
    course: "User Interface Design",
    lecture: 22,
    pages: 9,
  },
  {
    id: 8,
    name: "Git and GitHub Basics",
    course: "Version Control Systems",
    lecture: 12,
    pages: 4,
  },
  {
    id: 9,
    name: "Networking Fundamentals",
    course: "Computer Networks",
    lecture: 28,
    pages: 11,
  },
  {
    id: 10,
    name: "Creative Writing Prompts",
    course: "Writing Workshop",
    lecture: 14,
    pages: 6,
  },
];
